#!/bin/bash/env bash
# creates a file containing its PID

cleanup() {
  rm -f /var/run/myscript.pid
  exit
}

echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'; cleanup" SIGTERM
trap "echo 'Y U no love me?';cleanup" SIGINT
trap "cleanup" SIGQUIT SIGTERM


while true;do
	echo "To infinity and beyond"
	sleep 2
done
