#!/bin/bash
# Use awk to extract IP and HTTP status code from the Apache log file
# Then, use awk to count occurrences and print in the desired format
awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $2, $3}' | sort -nr
