#!/usr/bin/env bash
# This script displays different messages based on the loop iteration

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad Luck"
  elif [ $count -eq 8 ]
  then
    echo "good Luck"
  else
    echo "Best School"
  fi
  ((count++))
done
