#!/usr/bin/env bash
# This script displays numbers and messages based on the loop iteration

count=1
while [ $count -le 20 ]
do
  case $count in
    4)
      echo "$count and then bad luck from China"
      ;;
    9)
      echo "$count and then bad luck from Japan"
      ;;
    17)
      echo "$count and then bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
  esac
  ((count++))
done
