#!/usr/bin/env bash
# This script displays files in the current directory in a list format, showing only the part of the name after the first dash

for file in *; do
  # Check if the file is not hidden (doesn't start with a dot)
  if [[ $file != .* ]]; then
    # Use cut to extract the part after the first dash
    name_part=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name_part"
  fi
done
